title: "SovereignSolo AI"
tagline: "Engenharia de Negócios de Uma Pessoa Só com IA"
description: "Ebooks e estratégias de Marketing Digital de alta performance para empreendedores solo que utilizam automação por IA."
url: "https://kabbalahh.github.io"
baseurl: "https://kabbalahh.github.io/SovereignSolo-AI/index.html"

# Configurações de Compilação e SEO
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock